export const seedState = {
  accounts: [
    {
      id: "acct-001",
      name: "Atlas Industrial Supplies",
      country: "United States",
      city: "Houston",
      owner: "Lina",
      status: "active",
      lifecycle: "复购客户",
      source: "展会名片",
      industry: "机械设备",
      annualValue: 186000,
      lastContactAt: "2026-05-13",
      tags: ["VIP", "Machinery", "ODM"],
      risk: "低",
      nextAction: "确认 6 月批量订单交期",
      note: "采购节奏稳定，关注交付稳定性和售后响应速度。",
      contacts: [
        {
          name: "Mia Johnson",
          title: "Sourcing Director",
          email: "mia.johnson@example.com",
          phone: "+1 713 555 0198",
        },
      ],
    },
    {
      id: "acct-002",
      name: "Nordstern Handel GmbH",
      country: "Germany",
      city: "Hamburg",
      owner: "Chen",
      status: "prospect",
      lifecycle: "重点潜客",
      source: "Google Maps",
      industry: "建材家居",
      annualValue: 74000,
      lastContactAt: "2026-05-08",
      tags: ["New", "EU", "Private Label"],
      risk: "中",
      nextAction: "补充 CE 认证与德语包装资料",
      note: "首次询盘来自官网，偏好小批量试单和长期框架价。",
      contacts: [
        {
          name: "Jonas Weber",
          title: "Import Manager",
          email: "jonas.weber@example.de",
          phone: "+49 40 555 1902",
        },
      ],
    },
    {
      id: "acct-003",
      name: "Sahara Renewables",
      country: "United Arab Emirates",
      city: "Dubai",
      owner: "Maya",
      status: "active",
      lifecycle: "项目客户",
      source: "LinkedIn",
      industry: "新能源",
      annualValue: 132000,
      lastContactAt: "2026-05-11",
      tags: ["Energy", "Tender", "Arabic"],
      risk: "中",
      nextAction: "发送项目装箱方案与付款节点",
      note: "项目决策链较长，需要持续同步技术、财务和物流信息。",
      contacts: [
        {
          name: "Noura Khalid",
          title: "Project Buyer",
          email: "noura.khalid@example.ae",
          phone: "+971 4 555 0181",
        },
      ],
    },
    {
      id: "acct-004",
      name: "Pacifica Retail Group",
      country: "Australia",
      city: "Melbourne",
      owner: "Leo",
      status: "active",
      lifecycle: "成长客户",
      source: "老客转介绍",
      industry: "日用消费品",
      annualValue: 98000,
      lastContactAt: "2026-05-02",
      tags: ["Retail", "Repeat", "Seasonal"],
      risk: "低",
      nextAction: "确认圣诞季备货 SKU 清单",
      note: "季节性强，订单集中在 Q3，需要提前锁定产能。",
      contacts: [
        {
          name: "Oliver Smith",
          title: "Category Manager",
          email: "oliver.smith@example.au",
          phone: "+61 3 5550 1188",
        },
      ],
    },
    {
      id: "acct-005",
      name: "Andes Medical Partners",
      country: "Chile",
      city: "Santiago",
      owner: "Nina",
      status: "prospect",
      lifecycle: "样品客户",
      source: "B2B 询盘",
      industry: "医疗器械",
      annualValue: 52000,
      lastContactAt: "2026-04-28",
      tags: ["Medical", "Sample", "Spanish"],
      risk: "高",
      nextAction: "跟进样品反馈与注册文件",
      note: "采购标准严格，注册资料完整度决定推进速度。",
      contacts: [
        {
          name: "Camila Rojas",
          title: "Procurement Lead",
          email: "camila.rojas@example.cl",
          phone: "+56 2 555 0132",
        },
      ],
    },
  ],
  opportunities: [
    {
      id: "opp-001",
      accountId: "acct-001",
      title: "Packaging line renewal",
      product: "自动包装线配件",
      stage: "quote",
      value: 42000,
      probability: 68,
      expectedClose: "2026-06-08",
      owner: "Lina",
    },
    {
      id: "opp-002",
      accountId: "acct-002",
      title: "Private-label starter order",
      product: "浴室五金套装",
      stage: "sample",
      value: 18500,
      probability: 52,
      expectedClose: "2026-06-18",
      owner: "Chen",
    },
    {
      id: "opp-003",
      accountId: "acct-003",
      title: "Solar project phase one",
      product: "储能柜结构件",
      stage: "negotiation",
      value: 76000,
      probability: 82,
      expectedClose: "2026-05-30",
      owner: "Maya",
    },
    {
      id: "opp-004",
      accountId: "acct-004",
      title: "Holiday season reorder",
      product: "家居收纳用品",
      stage: "qualified",
      value: 31000,
      probability: 38,
      expectedClose: "2026-07-02",
      owner: "Leo",
    },
    {
      id: "opp-005",
      accountId: "acct-005",
      title: "Clinic sample validation",
      product: "一次性检测耗材",
      stage: "lead",
      value: 12800,
      probability: 20,
      expectedClose: "2026-06-25",
      owner: "Nina",
    },
  ],
  tasks: [
    {
      id: "task-001",
      accountId: "acct-001",
      title: "发送修订后的 PI 和装箱单",
      owner: "Lina",
      dueAt: "2026-05-14",
      status: "open",
      priority: "high",
    },
    {
      id: "task-002",
      accountId: "acct-002",
      title: "补充 CE 认证文件",
      owner: "Chen",
      dueAt: "2026-05-15",
      status: "open",
      priority: "medium",
    },
    {
      id: "task-003",
      accountId: "acct-003",
      title: "确认项目付款节点",
      owner: "Maya",
      dueAt: "2026-05-13",
      status: "open",
      priority: "high",
    },
    {
      id: "task-004",
      accountId: "acct-004",
      title: "整理 Q3 备货 SKU",
      owner: "Leo",
      dueAt: "2026-05-18",
      status: "done",
      priority: "low",
    },
  ],
  activities: [
    {
      id: "act-001",
      accountId: "acct-003",
      type: "email",
      title: "客户确认希望使用 FOB 深圳报价",
      createdAt: "2026-05-14T02:20:00.000Z",
    },
    {
      id: "act-002",
      accountId: "acct-001",
      type: "call",
      title: "电话确认 6 月订单数量上调 15%",
      createdAt: "2026-05-13T09:45:00.000Z",
    },
    {
      id: "act-003",
      accountId: "acct-002",
      type: "whatsapp",
      title: "买家要求补充德语安装说明",
      createdAt: "2026-05-12T15:10:00.000Z",
    },
  ],
  orders: [
    {
      id: "ord-001",
      accountId: "acct-001",
      code: "SO-2026-0412",
      amount: 58200,
      status: "生产中",
      eta: "2026-06-05",
      margin: 23,
    },
    {
      id: "ord-002",
      accountId: "acct-004",
      code: "SO-2026-0397",
      amount: 26400,
      status: "待收尾款",
      eta: "2026-05-28",
      margin: 19,
    },
    {
      id: "ord-003",
      accountId: "acct-003",
      code: "SO-2026-0388",
      amount: 44800,
      status: "验货预约",
      eta: "2026-05-24",
      margin: 27,
    },
  ],
};
